census-ecosystem/opencensus-go-exporter-stackdriver

stackdriver.go

The attributes are added to SpanData as long as there is not an existing
attribute on the span with the same key.
This is the requested alternative implementation to census-instrumentation/opencensus-go#750
refs census-instrumentation/opencensus-go#707

[trace] Add DefaultTraceAttributes

---

stats_test.go

Add the unit test on expectation of distribution

---

Gopkg.lock
Gopkg.toml
stats.go

Include OpenCensus base library version in user-agent header

---

Gopkg.lock
stats.go

A follow-up for https://github.com/census-instrumentation/opencensus-go/pull/781.

Use opencensus.Version() and gofmt

---

stats.go
stats_test.go

Remove the check for unique project ID within the process

---

stackdriver.go
stats.go
stats_test.go

Allow customizing the metric type

---

metrics.go
metrics_test.go
stats.go

A converter from Metrics to a monitoring/v3.MetricDescriptor
Updates #64.

metrics: Metrics to monitoring/v3.MetricDescriptor

---

metrics.go
metrics_test.go

A converter for:
OpenCensus Proto Resource
to
monitoredresource.Resource
Updates #64.

metrics: Proto Resource to monitoredresource.Resource

---

resource.go
resource_test.go
stackdriver.go
stats.go

Integrate with core resource and known detectors

---

monitoredresource/monitored_resources.go
monitoredresource/monitored_resources_test.go

Fixes https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/92.

Fix k8s_container resource labels.

---

monitoredresource/monitored_resources.go
monitoredresource/monitored_resources_test.go

Remove instance-id label from k8s_container resource.

---

equivalence_test.go
metrics.go
stackdriver.go

This reverts commit bf0d8a46b0afa4238b3d5c0eb1647f5e42a0d4cc.

Revert "change ExportMetric api to ExportMetricProto (#104)"

---

equivalence_test.go
metrics_proto.go
metrics_proto_test.go

Fix metric descriptor convertion.

---

monitoredresource/monitored_resources.go

fixes  https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/96

Fix an issue with multiple calls of Autodetec func

---

metrics_proto.go
metrics_proto_test.go

- convert summary.sum to cumulative_int64
- convert summary.count to cumulative_double
- convert summary.percentile to gauge with label "percentile"
fixes #151

convert summary metrics to cumulatives and gauges.

---

metrics_proto.go
metrics_proto_test.go

Copy resources when converting summary metrics.

---

stackdriver.go

print location detection error only when running on GCE.

---

equivalence_test.go

Use MetricServiceServer in fakeMetricService.

---

metrics_proto_test.go

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Remove unnecessary comment, check errors for PushMetricsProto

---

metrics_batcher.go

Follow-up of https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/213#discussion_r324907224.

Set a minimum size for reqsChan in batcher

---

stackdriver.go
trace.go

update PushTraceSpans to return dropped spans instead of good spans.

---

resource.go
resource_test.go

Default mapping for knative_broker and knative_trigger.

Default mapping for knative_broker and knative_trigger.
