census-ecosystem/opencensus-go-exporter-stackdriver

Gopkg.lock
Gopkg.toml

For versions before 1.0.0, dep will not match new minor releases.
Explicitly allow these since we know that the projects we depend on
will promise not to break this library.

Be more permissive in versions

---

stats.go
stats_test.go

When the aggregation type is view.LastValue, the metric kind should be GAUGE instead of CUMULATIVE.  Otherwise, it won't show the correct value on the UI of stackdriver backend.  Instead, it would show a value after some kind of processing by stackdriver.
Also modify and add a new test for the LastValue.  Already pass all the tests and run the go fmt.
Fixes: #15

LastValue should export as gauge metric kind

---

stats.go
stats_test.go

When the aggregation type is LastValue, the StartTime Field in the Point  is optional.  Remove it.

Remove the StartTime Field in the Point

---

example_test.go
label.go
stackdriver.go
stats.go
stats_test.go

* Introduce DefaultMonitoringLabels option
* Provide more documentation on how the exporter works with
Stackdriver Monitoring concepts (labels, time series, resources).
Fixes: #16

Allow customizing the set of default labels for stats exporting

---

stackdriver.go
stats.go
stats_test.go
trace.go

NewExporter now accepts context as its first argument like it's common,
and uses that context to establish grpc connections to Stackdriver.
Users can also provide a function returning a context that will be used
instead of context.Background() when metrics and traces are uploaded.
This fixes #27.

Allow users to provide context.

---

stackdriver.go
stats.go
stats_test.go

We were previously not checking for unset (zero) values in Options
before overriding the bundle delays in the bundler for the stats
portion of the exporter. Change this to only set the delays if
the values in the Options struct are non-zero, similar to what we
do for the trace exporter.

Do not use zero defaults for bundle delays

---

examples/stats/main.go

Fixes https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/36.

Update reporting period in the example to 60s.

---

stackdriver.go
stats.go
stats_test.go
trace.go
trace_test.go

Add a timeout (customizeable by option) to the contexts used to
make API calls (default to 2 seconds).
Add a size limit on spans we buffer in memory and compute the size
of the span by converting to protobuf before buffering, rather
than estimating from the SpanData struct.

Add timeouts; make span size buffer limit precise

---

metrics.go
metrics_test.go

An adapter to directly convert from OpenCensus Proto
Point to Stackdriver's monitoring/v3 Point which are
both protobuf based code backed representations.
This the first of a series of changes to allow direct
conversion of metrics so that we can use this exporter
in the OpenCensus Agent/Service exporters, but also so that
applications such as OpenCensus-PHP's daemon can begin to it too.
Updates #64.

OpenCensusProto Point to Stackdriver Point

---

equivalence_test.go
metrics.go
metrics_test.go
stackdriver.go
stats.go

Glued up the various methods and helpers to finally
expose ExportMetric which will be used to export
OpenCensus metrics to Stackdriver Monitoring.
Updates #64.

metrics: finished up metrics converter

---

equivalence_test.go
metrics.go
metrics_test.go
stats.go
stats_test.go

Since existence, the stats exporter was sending Stackdriver Metrics
only split up by chunks of maxUploadSize of 200, but Metric-s with the
exact same Type were still uploaded in the same CreateTimeSeriesRequest
which would cause:
err: rpc error: code = InvalidArgument desc = One or more TimeSeries could not be written:
Field timeSeries[?] had an invalid value: Duplicate TimeSeries encountered.
Only one point can be written per TimeSeries per request.: timeSeries[?]
and the previous remedy just relied on a synchronization of
SetReportingPeriod of 60+s which would aggregate stats/view.Data.
This change now splits up such Metrics so even if uploads are made
in less than 60s, CreateTimeSeriesRequest-s will be uniquely uploaded
and won't cause Stackdriver's backend to trip up.
Fixes #73

stats, metrics: deduplicate TimeSeries with non-unique Metric.Type

---

equivalence_test.go
metrics.go
stats.go

skip creating metric descriptor for stackdriver built-in metrics.

---

monitoredresource/gcp_metadata_config.go
monitoredresource/monitored_resources.go
monitoredresource/monitored_resources_test.go

this pull requests fixes https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/issues/49

Distinguish between gke_container and k8s_container monitored resource type

---

equivalence_test.go
metrics.go
stackdriver.go
stats.go

This is a breaking change but only consumer of this api is oc-agent. 
The api is renamed because this api should be used to export metric from core library to backends. After all, the api really exports metric proto and not metric data model.
The other change with this PR is taking slice of metrics instead of single metric. After that change there is no need for bundler. Hence it is removed.

Change ExportMetric api to ExportMetricProto

---

equivalence_test.go
go.sum

Similar change to https://github.com/census-ecosystem/opencensus-go-exporter-ocagent/pull/53.

Remove exemplar for now.

---

metrics.go
metrics_test.go
stackdriver.go
stats.go

This is the first PR to add support for exporting metrics. 
This will be followed by another PR to create a reader and start exporting (equivalent of registering exporter with view).

add support for exporting metrics data model

---

metrics_proto.go
metrics_proto_test.go
stats_test.go

Batch time series with different label values into same request.

---

equivalence_test.go
metrics_proto_test.go
metrics_test.go
metrics_test_utils.go

[go-cmp](https://github.com/google/go-cmp) is good at doing deeply comparison and showing the diffs. Use cmp instead of reflect and json, and refactor some test utils.

Use cmp instead of reflect and json in tests.

---

trace_proto.go
trace_proto_test.go

This will enable the OpenCensus service to write the `g.co/agent` label based on the library information of the written traces. Currently all trace written by the OC agent/collector have their agent set to look like they are using the Go library.
See https://github.com/census-instrumentation/opencensus-service/issues/525 for context.

Don't overwrite agent label if already set

---

metrics.go
metrics_test.go

This fixes #133 if you use 
```go
MonitoredResource: monitoredresource.Autodetect(),
```
If you use 
```go
ResourceDetector:  auto.Detect,
```
then it only detects GCE and not GKE. This because auto.Detect doesn't support GKE. Opened #140 to track this.

Fix resource assignment in GKE and GCE environment when using metrics exporter.

---

go.mod
go.sum
metrics.go

this change is in coordination with metrics api change in [PR](https://github.com/census-instrumentation/opencensus-go/pull/1114).

add support for label key description.

---

metrics.go
metrics_test.go

~~DO NOT MERGE until the exemplar PRs at core library are merged.~~

Support exporting Exemplar.

---

equivalence_test.go
metrics_proto.go
metrics_proto_test.go

Fixes https://github.com/census-instrumentation/opencensus-service/issues/542.
This change is to preserve the original identifier of the processes that send proto metrics to Agent. See https://github.com/census-instrumentation/opencensus-service/issues/542#issuecomment-490644254.

Add opencensus_task labels to proto metrics if no default labels are provided.

---

equivalence_test.go
metrics_proto.go
metrics_proto_test.go
resource.go
resource_test.go

transform resources for metrics exported via ExportMetricsProto api

---

go.mod
go.sum
metrics_proto_test.go
resource.go
resource_test.go

This change along with [change](https://github.com/census-ecosystem/opencensus-go-resource/pull/12) in resource package fixes #159 .

use container type instead of k8s type for resource transfomation

---

stats.go

This would prematurely cancel the context used for dialling the gRPC service since grpc.DialContext() is non-blocking. The result was confusing "Unauthenticated" error messages when attempting to upload metrics.
Instead, make the client connection in `newStatsExporter()` the same as `newTraceExporter()` where a simple background context is used when creating the client. Change was originally introduced in #58.
Fixes #61.

Don't use a timeout context when creating the metrics client.

---

metrics_proto.go

This PR fixes error handling for metrics proto upload. It adds error message when uploading metrics proto similar to all other uploads. Without this pushing metrics can fail without any log information.
All other `handle*` functions call `handleError` when encountered error.

Fix handling errors in when failing to upload metrics proto

---

resource.go
resource_test.go

Added support for mapping kubernetes pod resource, as described here: https://cloud.google.com/monitoring/api/resources#tag_k8s_pod.
Also, do you know what's the correct way of adding support for kubernetes node resource?

Add mapping for kubernetes pod

---

metrics_proto.go
metrics_proto_test.go
metrics_test_utils.go

Otherwise Stackdriver backend **may** not be able to set metric or value types correctly.

Set MetricKind and ValueType when sending TimeSeries

---

examples/stats/main.go

Updates https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/188#issuecomment-526456067

fix example to use new api to start and stop exporting.

---

equivalence_test.go
example_test.go
stackdriver.go
stackdriver_test.go
stats.go
stats_test.go

This reverts commit 4b7f30648a4f2cf529cecb4274f016b9cc30df7e.
#188 has caused some issues to those who still use the old interface. It should be better to follow the standard deprecation policy (https://github.com/census-instrumentation/opencensus-go#deprecation-policy) before we remove it.

Revert "Remove support for exporting ViewData (#188)"

---

stats.go

This must be used for the reader to be initialized properly.
Fixes #170

Use NewReader for metrics reader init

---

examples/stats/main.go

Otherwise Stackdriver will return an error saying buckets don't match with bucket bounds.

Remove leading 0 in histogram buckets in example

---

metrics_proto_test.go

Signed-off-by: Bogdan Drutu <bogdandrutu@gmail.com>

Do not try to start trace exporter in TestExportTimeSeriesWithDifferentLabels

---

equivalence_test.go

On some environments using ":port" addresses may generate ErrAddressFamilyNotSupported.

Use complete address when return from create fake server

---

equivalence_test.go

It turns out we need to explicitly set `Insecure` when connecting to a fake Stackdriver server. 
Also improve the test to fail when timeseries is not exported.

Fix equivalence test

---

metrics_proto_api_test.go

add test to handle multiple timeseries for Summary metrics.

---

metrics_proto_api_test.go
resource.go
resource_test.go

fixes #218 
It also changes for comments from PR #215 that were left out prior to merge.

add resource detector test.

---

metrics_proto_api_test.go
testdata/BuiltInMetrics/inMetrics.txt
testdata/BuiltInMetrics/outMDR.txt
testdata/BuiltInMetrics/outTSR.txt

added test for 
- per metric resource
- built-in metrics
- metric prefix.

Resource per metric

---

metrics.go
metrics_test.go
stackdriver.go

Add option to provide resource based on metric descriptor.

---

metrics.go

stop ignoring errors while processing metrics.

---

metrics_proto.go
metrics_proto_api_test.go
metrics_proto_test.go
stackdriver.go
stats.go

Fix #237.
* Add `GetMetricPrefix` option to decide metric prefix based on metric name.
* Add "knative.dev" to supported domains.
* Update `MetricPrefix` description and stop using it for display name.

Add GetMetricPrefix func as an option to support dynamic custom metric prefix

---

resource.go
resource_test.go
stackdriver.go

The location label is required. The resource type mappings defined in resource.go uniformly expect `resourcekeys.CloudKeyZone`, except the `generic_task`, but there is no good reason for that, as Stackdriver still requires a valid cloud location for `generic_task`. Therefore, use a cloud location everywhere.
This makes the exporter work out-of-the-box in conjuction with `kubernetes-operator` and partially addresses https://github.com/census-ecosystem/kubernetes-operator/issues/14
@rghetia please review.

Use standard label name for location.

---

stackdriver.go
trace.go
trace_test.go

In situations where a large number of spans need to be exported from a
single instance of the exporter, bundle uploads are limited to using a
single goroutine. This limits the overall throughput of the exporter.
Make use of the NumberOfWorkers option to allow the exporter to use
multiple, concurrent goroutines to upload spans to Stackdriver.
Closes #245.
Signed-off-by: Nick Travers <n.e.travers@gmail.com>

trace: allow for concurrent uploads to Stackdriver

---

monitoredresource/aws/aws_identity_doc_utils.go
monitoredresource/aws/monitored_resources.go
monitoredresource/aws/monitored_resources_test.go
monitoredresource/deprecated.go
monitoredresource/deprecated_test.go
monitoredresource/gcp/gcp_metadata_config.go
monitoredresource/gcp/monitored_resources.go
monitoredresource/gcp/monitored_resources_test.go
monitoredresource/monitored_resources.go
resource.go
resource_test.go
stackdriver_test.go

Changes:
- Add default mapping for the [knative_revision](https://cloud.google.com/monitoring/api/resources#tag_knative_revision) Monitored Resource type
- During resource mapping, attempt to autodetect as many monitored resource labels as possible from monitoredresource.Autodetect
Using just some of the autodetected labels allows users of the Stackdriver exporter to avoid duplicating the Google-specific logic in monitoredresource.Autodetect. 
This is useful for codebases like Knative which can run on any k8s platform and would like to avoid embedding cloud-provider-specific code in the codebase (https://github.com/knative/pkg/blob/master/metrics/README.md).

Default mapping for knative_revision & autodetect labels

---

equivalence_test.go
metrics_proto_test.go
resource.go
resource_test.go
stackdriver.go

In case there is a need to handle extra resource types, it's useful to be able to keep the original behavior, e.g.
```go
func myMapResource(res *resource.Resource) *monitoredrespb.MonitoredResource {
if res.Type == "my-resource-type" {
// custom handling
...
return result
}
// otherwise return default result
return stackdriver.DefaultMapResource(res)
}
```

Make defaultMapResource function public to allow reusing it in custom functions

---

stats.go

Stop including artificial 0 bound when existing lowest bound is negative

---

stackdriver.go

Fixes the following error when the `labels` is not initialized:
```
Container logs:
level=info ts=2020-03-02T03:17:42.590Z caller=main.go:293 msg="Starting Stackdriver Prometheus sidecar" version="(version=0.7.3, branch=master, revision=2548e8a7b383adc9217afe8570247ea84e3ef2c0)"
level=info ts=2020-03-02T03:17:42.591Z caller=main.go:294 build_context="(go=go1.12, user=kbuilder@kokoro-gcp-ubuntu-prod-40088225, date=20200206-15:24:17)"
level=info ts=2020-03-02T03:17:42.591Z caller=main.go:295 host_details="(Linux 4.14.138+ #1 SMP Tue Sep 3 02:58:08 PDT 2019 x86_64 apigee-metrics-v111-fd6fj (none))"
level=info ts=2020-03-02T03:17:42.592Z caller=main.go:296 fd_limits="(soft=1048576, hard=1048576)"
panic: assignment to entry in nil map
```
Labels can be optionally extracted from …

Initialize the labels map in the response.

---

metrics.go
metrics_test.go

We shouldn't set the labels if the  value is not present.
This is necessary for the current knative work with multiple meters.  In knative some metric labels are extracted into resource labels, so we shouldn't set those metric labels.
https://github.com/evankanderson/knative-pkg/blob/resourcefullest/metrics/stackdriver_exporter.go#L239

Check .Present before setting label value

---

metrics_proto_test.go
stats.go

This is a quick fix (though a bit hacky) for the following problem: when a metric name is prefixed with a custom domain, the generated display name is pretty long and confusing.
e.g. for metric `external.googleapis.com/user/my_metric` the display name is `OpenCensus/external.googleapis.com/user/my_metric`.
Also, since we use this exporter in OpenTelemetry collector, having `OpenCensus/` as a prefix on all metrics is pretty confusing as well.
This fix just removes the redundant `OpenCensus/` prefix from such metrics as a quick workaround.
Ideally we may want to also consider removing domain from the display name as well, but that requires more changes in configuration and overall code.

Skip adding display name prefix for metrics with custom domain

---

metrics_batcher.go
metrics_batcher_test.go

See the test case for an example of a partial success response

Parse dropped timeseries from Create Timeseries Response

---

stackdriver.go

This is useful if you want to use your code as source of truth of
MetricDescritors.
Managing MetricDescriptors outside of the Go code (e.g. in Terraform
configs) is painful, as the changes to MD requires delete/recreate,
after deleting all alert policies associated with the metric. On the
other hand, the externally managed MDs are bound to be out of sync with
what's present in the code.
In the end we decide to just extract/collect views from our go code as
source of truth, and thus we need to have a public method to convert
views to MD.

Add a public method to convert OpenCensus View to MetricDescriptor.

---

resource.go
resource_test.go

While converting an ocagent resource to a cloud resource, stackdriver
exporter looks for a set of labels that apply to a generic_task resource:
https://cloud.google.com/monitoring/api/resources#tag_generic_task
However, if it doesn't find one of the labels, it falls back to "global"
resource with just the project id label, and it works OK.
But if it does find all of the labels, it will attach them to the exported
resource, and Cloud API fails with "Unrecognized resource label" error,
because those labels do not exist on a "global" resource.
Changing "global" to "generic_task" fixes this situation.

Use generic_task resource type when all generic labels are present

---

monitoredresource/deprecated_test.go
monitoredresource/gcp/gcp_metadata_config.go
monitoredresource/gcp/monitored_resources.go
monitoredresource/gcp/monitored_resources_test.go

Full details: https://cloud.google.com/stackdriver/docs/deprecations/legacy
Legacy (i.e. Monitoring v1) was deprecated in December 2019 and decommissioned March 2021.

Remove support for legacy GKE monitoring resource model

---

metrics_proto.go
metrics_proto_test.go
metrics_test.go
testdata/BuiltInMetrics/inMetrics.txt
testdata/BuiltInMetrics/outTSR.txt
testdata/ExportLabels/inMetrics.txt
testdata/ExportLabels/outTSR.txt
testdata/ExportMetricsOfAllTypes/inMetrics.txt
testdata/ExportMetricsOfAllTypes/outTSR.txt
testdata/SingleMetric/inMetrics.txt
testdata/SingleMetric/outTSR.txt
testdata/TwoMetrics/inMetrics.txt
testdata/TwoMetrics/outTSR.txt

Similarly to #287 we should add the staggering between the start and end time when handling data in PushMetricsProto call.

Add staggering between identical start and end times in metric in PushMetricsProto call

---

go.sum
stackdriver.go
stackdriver_test.go

Follow-up to https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/pull/295.  If using an Insecure client with the OpenTelemetry collector, [it will use](https://github.com/open-telemetry/opentelemetry-collector-contrib/blob/main/exporter/googlecloudexporter/googlecloud.go#L72) the `WithGRPCConn` option.  This grpc connection is then used for both the trace and stats clients.  When closing the exporter, the second `Close()` call fails with `error(s) closing trace client (<nil>), or metrics client (rpc error: code = Canceled desc = grpc: the client connection is closing)`, which indicates the connection is already closed.  Handle this case by ignoring that error.
This is required to fix unit test errors in https://github.com/open-telemetry/opentelemetry-collector-contrib/pu …

Handle the case where grpc client connections are shared

---

stats.go

We noticed that under high load the exporter allocates a lot of memory in those clone calls.
Even when the splitting is not needed.
While the splitting should be gated by a flag in general, this small fix will already remedy our biggest issue and disabling the split in general can be considered further down the road.

avoid expensive clones in splitCreateTimeSeriesRequest

---

go.mod
go.sum
metrics_proto.go

In some versions of the opentelemetry collector (between v0.30.0 and v0.42.0), staleness markers are passed along to exporters from the receiver.  We can simply ignore those points.

Ignore staleness markers

---

metrics.go
metrics_test.go

Attempting to create metrics with unspecified metricKind floods GCP logs with the following error: "Request was missing field metricDescriptor.metricKind: The descriptor does not have the metric kind set."
This will happen when metric type is of TypeSummary.

Prevent from attempting to create metrics with unspecified MetricKind

---

stackdriver_test.go
util_test.go

Remove `ioutil` that has been deprecated since Go 1.16

Remove deprecated ioutil
